### ISSUE TITLE
Add basic eslint + prettier to this precommit flow as well

### ISSUE THREAD

**Issue by Alex-Mann** [sudo-suhas/lint-staged-multi-pkg#1]
Great example repo! I think it would also be useful to document how adding `eslint` and `prettier` would be added to this as well.

For example, you likely have one `.prettierrc` file because you want your JS code to read the same throughout, but you could have multiple `.eslintrc` files for each project based on different settings.

**Comment by sudo-suhas** [comment]
Hey @Alex-Mann, thank you. This repo is to mainly show how `lint-staged` can be used in a monorepo. And both projects already have their own `.eslintrc.yml` file(although the config itself is not different). And I have intentionally added the least amount of things possible. I use `prettier` in almost all projects but I don't think it is needed here.
