### ISSUE TITLE
Execute lint-staged for files outside of packages

### ISSUE THREAD

**Issue by fabb** [sudo-suhas/lint-staged-multi-pkg#20]
I wonder how to best execute lint-staged on files outside of the packages? E.g. for running `prettier` on the root `package.json`. I guess it would be best to put the lint-staged config to the root package.json and use [exclude glob patterns](https://github.com/okonet/lint-staged/blob/master/README.md#filtering-files) to exclude the lerna packages folder?

**Comment by sudo-suhas** [comment]
See https://github.com/okonet/lint-staged#can-i-lint-files-outside-of-the-current-project-folder
