### ISSUE TITLE
Docs: Why use lerna run --concurrency 1?

### ISSUE THREAD

**Issue by pwrnrd** [sudo-suhas/lint-staged-multi-pkg#31]
Thank you for creating this repo! It helped me a lot! 

You documented everything very well, I only have one question: why is `lerna` not run in parallel? Is it because this might mess up the logs?

Perhaps it would be nice to add the reasoning to the README.md?

**Comment by sudo-suhas** [comment]
It is mentioned already:

> concurrent execution is disabled because it can cause problems during git add (see okonet/lint-staged#225).
