### ISSUE TITLE
Execute lint-staged only in package where there are staged changes

### ISSUE THREAD

**Issue by jogold** [sudo-suhas/lint-staged-multi-pkg#4]
Hi,

It seems that with the proposed structure `precommit` is run in each package even those that don't have staged changes. Any idea on how to improve this?

**Comment by sudo-suhas** [comment]
You could try [installing `lint-staged` at the package root](https://github.com/sudo-suhas/lint-staged-multi-pkg#install-lint-staged-at-the-package-root).

**Comment by sudo-suhas** [comment]
The `precommit` call to package which does not have any staged file would be effectively a no-op via `lint-staged` if I am not wrong.

**Comment by jogold** [comment]
> The `precommit` call to package which does not have any staged file would be effectively a no-op via `lint-staged` if I am not wrong.

It is a no-op but for a monorepo with let's say 30 packages it's a very slow process...

**Comment by sudo-suhas** [comment]
Go through these:
- https://github.com/lerna/lerna/issues/1263
- https://github.com/lerna/lerna/tree/master/commands/run#readme
- https://www.npmjs.com/package/@lerna/filter-options

You should be able to tweak `lerna run` to pick only the packages which have been modified.

**Comment by sudo-suhas** [comment]
If you are arrive at a solution, would you be interested in contributing to the readme by adding a FAQ section? I think the question your question is worth documenting.

**Comment by jogold** [comment]
> would you be interested in contributing to the readme by adding a FAQ section?

of course

**Comment by jogold** [comment]
https://github.com/lerna/lerna/issues/1955

**Comment by jogold** [comment]
Ever tried this https://github.com/wix-incubator/monorepo-staged-precommit?

**Comment by sudo-suhas** [comment]
No, I haven't tried that. To be completely honest, I have never used a monorepo myself. I originally authored this as an example for usage of `lint-staged`.

**Comment by sudo-suhas** [comment]
@jogold Could you try adding ` --since HEAD` to your pre-commit command? I think this might do the trick.

Edit: This will run the pre-commit hook for a package if it has _any_ changes. Even if they haven't been staged. It's still better than the current behavior though.

**Comment by jogold** [comment]
@sudo-suhas I ended up doing this: https://github.com/goldwasserexchange/public/blob/chore/global/monorepo/precommit.js

with this:
```json
{
 "husky": {
    "hooks": {
      "pre-commit": "node precommit.js"
    }
  }
}
```

**Comment by dialex** [comment]
@jogold that `precommit.js` file returns a 404

**Comment by jogold** [comment]
@dialex have a look here https://github.com/goldwasserexchange/public/blob/master/precommit.js
